config/routes.rb
Rails.application.routes.draw do
	get 'farmago/index'
	get 'farmago/search'
	get 'farmago/drugs'
	get 'farmago/leaflet'

  root 'farmago#index'

end

app/models/refunded_drug.rb
class RefundedDrug < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/farmago_controller.rb
require 'net/http'
require 'open-uri'
require 'timeout'


class FarmagoController < ApplicationController
	def drugs
		@drugs = RefundedDrug.all
		render json: @drugs
  	end

	def search
		#YourModelName.where("yourFieldName like ?", "%" + yourSearchTerm + "%")
		s = "%" + params[:search] + "%"
		@drugs = RefundedDrug.where("drug_name LIKE ? OR active_substance LIKE ? OR limited_group LIKE ? OR indications_range LIKE ? OR other_indications LIKE ?", s, s, s, s, s)
    	render search: params[:search].inspect
	end

	def leaflet
		begin
			status = Timeout::timeout(5) {
				tmp_path = "tmp/"
				base_url = "http://leki.urpl.gov.pl"
				uri = URI.parse(base_url + "/index.php")
				http = Net::HTTP.new(uri.host, uri.port)

				request = Net::HTTP::Post.new(uri.request_uri)
				request.set_form_data({"szukacz" => params[:ean], "kategoria" => "EAN"})

				response = http.request(request)
				pdf_re = /\"window\.open\('\/\w+\/\w+.pdf'\)\"/  
				match = pdf_re.match(response.body)
		
				pdf_from_match = match[0].split("'")[1]
				pdf_file_name = File.basename(pdf_from_match)
				pdf_url = base_url + pdf_from_match

				open(tmp_path + pdf_file_name, 'wb') do |file|
  					file << open(pdf_url).read
				end

				result = system("pdftohtml " + tmp_path + pdf_file_name)
				base_name = pdf_file_name.split(".")[0]
				html_file_path = tmp_path + base_name + "s.html"

				render :file => html_file_path
			}
		rescue
			render :file => "app/views/farmago/brak_ulotki.html"
		end
	end

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/farmago_helper.rb
module FarmagoHelper
end

app/views/farmago/index.html.erb
<h1>Farmago</h1>

<%= form_tag(farmago_search_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Szukaj leku" %>
  <%= submit_tag "Szukaj", :name => nil %>
<% end %>

app/views/farmago/search.html.erb
<h1>Farmago</h1>

<%= form_tag(farmago_search_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], autofocus: true, placeholder: "Szukaj leku" %>
  <%= submit_tag "Szukaj", :name => nil %>
<% end %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @drugs.each do |drug| %>
    <tr>
      <td><%= drug.active_substance %></td>
      <td><%= drug.drug_name %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Farmago</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>